all:
	@make --no-print-directory -C PACMAN
	@make --no-print-directory -C NIBBLER

clean:
	@make clean  --no-print-directory -C PACMAN
	@make clean  --no-print-directory -C NIBBLER

fclean:
	@make fclean  --no-print-directory -C PACMAN
	@make fclean  --no-print-directory -C NIBBLER

re:
	@make re  --no-print-directory -C PACMAN
	@make re  --no-print-directory -C NIBBLER
