all:
	@make --no-print-directory -C NCURSES
	@make --no-print-directory -C SFML
	@make --no-print-directory -C OPENGL

clean:
	@make clean  --no-print-directory -C NCURSES
	@make clean  --no-print-directory -C SFML
	@make clean  --no-print-directory -C OPENGL

fclean:
	@make fclean  --no-print-directory -C NCURSES
	@make fclean  --no-print-directory -C SFML
	@make fclean  --no-print-directory -C OPENGL

re:
	@make re  --no-print-directory -C NCURSES
	@make re  --no-print-directory -C SFML
	@make re  --no-print-directory -C OPENGL
